"""Refactor professional model; add services and many-to-many table; minor changes to activity_enrollments

Revision ID: 31e8f8ceb080
Revises: f88150a57560
Create Date: 2025-07-23 14:53:28.143570

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31e8f8ceb080'
down_revision = 'f88150a57560'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('services',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_pami_covered', sa.Boolean(), nullable=True),
    sa.Column('default_fee', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('status', sa.Enum('ACTIVO', 'SUSPENDIDO', 'CANCELADO', name='activitystatus'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('professional_services',
    sa.Column('professional_id', sa.Integer(), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.Column('custom_fee', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('notes', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['professional_id'], ['professionals.id'], ),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ),
    sa.PrimaryKeyConstraint('professional_id', 'service_id')
    )
    with op.batch_alter_table('activity_enrollments', schema=None) as batch_op:
        batch_op.drop_column('id')
        batch_op.drop_column('status')

    with op.batch_alter_table('professionals', schema=None) as batch_op:
        batch_op.drop_column('profession')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('professionals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profession', sa.VARCHAR(length=18), nullable=False))

    with op.batch_alter_table('activity_enrollments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.VARCHAR(length=10), nullable=False))
        batch_op.add_column(sa.Column('id', sa.INTEGER(), nullable=False))

    op.drop_table('professional_services')
    op.drop_table('services')
    # ### end Alembic commands ###
