"""Fix one-to-many relationship: Activity -> Teachers

Revision ID: 371702d6d09c
Revises: 3c07850594b0
Create Date: 2025-06-11 08:52:18.526968

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '371702d6d09c'
down_revision = '3c07850594b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.drop_column('teacher_dni')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.add_column(sa.Column('teacher_dni', sa.VARCHAR(length=8), nullable=False))
        batch_op.create_foreign_key(None, 'teachers', ['teacher_dni'], ['dni'])

    # ### end Alembic commands ###
