"""First migration: Creating base tables.

Revision ID: 3abdd02d4e80
Revises: 
Create Date: 2025-06-06 16:23:07.602814

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3abdd02d4e80'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('members',
    sa.Column('first_names', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('pami_number', sa.String(length=14), nullable=True),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('address', sa.String(length=200), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('join_date', sa.Date(), nullable=False),
    sa.Column('dni', sa.String(length=8), nullable=False),
    sa.Column('gender', sa.String(length=1), nullable=False),
    sa.PrimaryKeyConstraint('dni'),
    sa.UniqueConstraint('dni'),
    sa.UniqueConstraint('pami_number')
    )
    op.create_table('professionals',
    sa.Column('first_names', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('license_number', sa.String(length=20), nullable=True),
    sa.Column('profession', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('address', sa.String(length=200), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('join_date', sa.Date(), nullable=False),
    sa.Column('dni', sa.String(length=8), nullable=False),
    sa.Column('gender', sa.String(length=1), nullable=False),
    sa.PrimaryKeyConstraint('dni'),
    sa.UniqueConstraint('dni'),
    sa.UniqueConstraint('license_number')
    )
    op.create_table('teachers',
    sa.Column('activity_id', sa.Integer(), nullable=False),
    sa.Column('first_names', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('address', sa.String(length=200), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('join_date', sa.Date(), nullable=False),
    sa.Column('dni', sa.String(length=8), nullable=False),
    sa.Column('gender', sa.String(length=1), nullable=False),
    sa.PrimaryKeyConstraint('dni'),
    sa.UniqueConstraint('dni')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('teachers')
    op.drop_table('professionals')
    op.drop_table('members')
    # ### end Alembic commands ###
