"""Restore pami_number column.

Revision ID: 6bc6a90a0d8d
Revises: ced182afff57
Create Date: 2025-06-11 18:42:23.311196

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6bc6a90a0d8d'
down_revision = 'ced182afff57'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('members', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pami_number', sa.String(length=14), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('members', schema=None) as batch_op:
        batch_op.drop_column('pami_number')

    # ### end Alembic commands ###
