"""Correct email field to member.

Revision ID: 85fcbb071c08
Revises: 371702d6d09c
Create Date: 2025-06-11 14:26:27.708343

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85fcbb071c08'
down_revision = '371702d6d09c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=9),
               type_=sa.Enum('ACTIVO', 'SUSPENDIDO', 'CANCELADO', name='activitystatus'),
               existing_nullable=False)

    with op.batch_alter_table('activity_enrollments', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=9),
               type_=sa.Enum('ACTIVO', 'SUSPENDIDO', 'CANCELADO', name='activitystatus'),
               existing_nullable=False)

    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=9),
               type_=sa.Enum('PROGRAMADO', 'COMPLETADO', 'CANCELED', name='appointmentstatus'),
               existing_nullable=False)

    with op.batch_alter_table('members', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=100), nullable=True))
        batch_op.alter_column('gender',
               existing_type=sa.VARCHAR(length=6),
               type_=sa.Enum('M', 'F', name='gender'),
               existing_nullable=False)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=9),
               type_=sa.Enum('ACTIVO', 'SUSPENDIDO', 'ELIMINADO', name='personstatus'),
               existing_nullable=False)

    with op.batch_alter_table('professionals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=100), nullable=True))
        batch_op.alter_column('profession',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('ABOGADO', 'ENFERMERO', 'REFLEXÓLOGA', 'MÉDICO_DE_CABECERA', 'NUTRICIONISTA', 'PSICÓLOGO', 'PSIQUIATRA', 'PODÓLOGO', name='profession'),
               existing_nullable=False)
        batch_op.alter_column('gender',
               existing_type=sa.VARCHAR(length=6),
               type_=sa.Enum('M', 'F', name='gender'),
               existing_nullable=False)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=9),
               type_=sa.Enum('ACTIVO', 'SUSPENDIDO', 'ELIMINADO', name='personstatus'),
               existing_nullable=False)

    with op.batch_alter_table('teachers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=100), nullable=True))
        batch_op.alter_column('gender',
               existing_type=sa.VARCHAR(length=6),
               type_=sa.Enum('M', 'F', name='gender'),
               existing_nullable=False)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=9),
               type_=sa.Enum('ACTIVO', 'SUSPENDIDO', 'ELIMINADO', name='personstatus'),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teachers', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.Enum('ACTIVO', 'SUSPENDIDO', 'ELIMINADO', name='personstatus'),
               type_=sa.VARCHAR(length=9),
               existing_nullable=False)
        batch_op.alter_column('gender',
               existing_type=sa.Enum('M', 'F', name='gender'),
               type_=sa.VARCHAR(length=6),
               existing_nullable=False)
        batch_op.drop_column('email')

    with op.batch_alter_table('professionals', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.Enum('ACTIVO', 'SUSPENDIDO', 'ELIMINADO', name='personstatus'),
               type_=sa.VARCHAR(length=9),
               existing_nullable=False)
        batch_op.alter_column('gender',
               existing_type=sa.Enum('M', 'F', name='gender'),
               type_=sa.VARCHAR(length=6),
               existing_nullable=False)
        batch_op.alter_column('profession',
               existing_type=sa.Enum('ABOGADO', 'ENFERMERO', 'REFLEXÓLOGA', 'MÉDICO_DE_CABECERA', 'NUTRICIONISTA', 'PSICÓLOGO', 'PSIQUIATRA', 'PODÓLOGO', name='profession'),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
        batch_op.drop_column('email')

    with op.batch_alter_table('members', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.Enum('ACTIVO', 'SUSPENDIDO', 'ELIMINADO', name='personstatus'),
               type_=sa.VARCHAR(length=9),
               existing_nullable=False)
        batch_op.alter_column('gender',
               existing_type=sa.Enum('M', 'F', name='gender'),
               type_=sa.VARCHAR(length=6),
               existing_nullable=False)
        batch_op.drop_column('email')

    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.Enum('PROGRAMADO', 'COMPLETADO', 'CANCELED', name='appointmentstatus'),
               type_=sa.VARCHAR(length=9),
               existing_nullable=False)

    with op.batch_alter_table('activity_enrollments', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.Enum('ACTIVO', 'SUSPENDIDO', 'CANCELADO', name='activitystatus'),
               type_=sa.VARCHAR(length=9),
               existing_nullable=False)

    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.Enum('ACTIVO', 'SUSPENDIDO', 'CANCELADO', name='activitystatus'),
               type_=sa.VARCHAR(length=9),
               existing_nullable=False)

    # ### end Alembic commands ###
