"""Add new tables.

Revision ID: 866f54d42f3e
Revises: 3abdd02d4e80
Create Date: 2025-06-06 17:30:19.313553

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '866f54d42f3e'
down_revision = '3abdd02d4e80'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activities',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('schedule', sa.String(length=100), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('capacity', sa.Integer(), nullable=True),
    sa.Column('teacher_id', sa.String(length=8), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.dni'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('appointments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('member_dni', sa.String(length=8), nullable=False),
    sa.Column('professional_dni', sa.String(length=8), nullable=False),
    sa.Column('appointment_date', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['member_dni'], ['members.dni'], ),
    sa.ForeignKeyConstraint(['professional_dni'], ['professionals.dni'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('member_id', sa.String(length=8), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('period', sa.Date(), nullable=False),
    sa.Column('payment_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['member_id'], ['members.dni'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('activity_enrollments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('member_dni', sa.String(length=8), nullable=False),
    sa.Column('activity_id', sa.Integer(), nullable=False),
    sa.Column('enrollment_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['activity_id'], ['activities.id'], ),
    sa.ForeignKeyConstraint(['member_dni'], ['members.dni'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('activity_enrollments')
    op.drop_table('payments')
    op.drop_table('appointments')
    op.drop_table('activities')
    # ### end Alembic commands ###
