"""Drop unique constraint in 'pami_number'.

Revision ID: ced182afff57
Revises: 85fcbb071c08
Create Date: 2025-06-11 18:30:30.832546

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ced182afff57'
down_revision = '85fcbb071c08'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('members', schema=None) as batch_op:
        batch_op.drop_column('pami_number')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('members', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pami_number', sa.VARCHAR(length=14), nullable=True))

    # ### end Alembic commands ###
