"""Remove appointments table.

Revision ID: ed7e71e130f8
Revises: 6bc6a90a0d8d
Create Date: 2025-06-12 13:23:10.153982

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed7e71e130f8'
down_revision = '6bc6a90a0d8d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('appointments')
    with op.batch_alter_table('professionals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('schedule', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('professionals', schema=None) as batch_op:
        batch_op.drop_column('schedule')

    op.create_table('appointments',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('member_dni', sa.VARCHAR(length=8), nullable=False),
    sa.Column('professional_dni', sa.VARCHAR(length=8), nullable=False),
    sa.Column('appointment_date', sa.DATETIME(), nullable=False),
    sa.Column('status', sa.VARCHAR(length=10), nullable=False),
    sa.ForeignKeyConstraint(['member_dni'], ['members.dni'], ),
    sa.ForeignKeyConstraint(['professional_dni'], ['professionals.dni'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
