"""Create most of the tables.

Revision ID: f3df0a3adb1e
Revises: 
Create Date: 2025-06-09 19:21:13.723766

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3df0a3adb1e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('members',
    sa.Column('pami_number', sa.String(length=14), nullable=True),
    sa.Column('dni', sa.String(length=8), nullable=False),
    sa.Column('gender', sa.Enum('MALE', 'FEMALE', name='gender'), nullable=False),
    sa.Column('first_names', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('address', sa.String(length=200), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'SUSPENDED', 'DELETED', name='personstatus'), nullable=False),
    sa.Column('join_date', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('dni'),
    sa.UniqueConstraint('dni'),
    sa.UniqueConstraint('pami_number')
    )
    op.create_table('professionals',
    sa.Column('license_number', sa.String(length=20), nullable=True),
    sa.Column('profession', sa.Enum('LAWYER', 'NURSE', 'MASSEUR', 'GENERAL_PRACTITIONER', 'NUTRITIONIST', 'PSYCHOLOGIST', 'PSYCHIATRIST', 'PODOLOGIST', name='profession'), nullable=False),
    sa.Column('dni', sa.String(length=8), nullable=False),
    sa.Column('gender', sa.Enum('MALE', 'FEMALE', name='gender'), nullable=False),
    sa.Column('first_names', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('address', sa.String(length=200), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'SUSPENDED', 'DELETED', name='personstatus'), nullable=False),
    sa.Column('join_date', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('dni'),
    sa.UniqueConstraint('dni'),
    sa.UniqueConstraint('license_number')
    )
    op.create_table('teachers',
    sa.Column('activity_id', sa.Integer(), nullable=False),
    sa.Column('dni', sa.String(length=8), nullable=False),
    sa.Column('gender', sa.Enum('MALE', 'FEMALE', name='gender'), nullable=False),
    sa.Column('first_names', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('address', sa.String(length=200), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'SUSPENDED', 'DELETED', name='personstatus'), nullable=False),
    sa.Column('join_date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['activity_id'], ['activities.id'], name='fk_teacher_activity', deferrable=True, use_alter=True),
    sa.PrimaryKeyConstraint('dni'),
    sa.UniqueConstraint('dni')
    )
    op.create_table('activities',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('schedule', sa.String(length=100), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('capacity', sa.Integer(), nullable=True),
    sa.Column('teacher_dni', sa.String(length=8), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'SUSPENDED', 'CANCELED', name='activitystatus'), nullable=False),
    sa.ForeignKeyConstraint(['teacher_dni'], ['teachers.dni'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('appointments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('member_dni', sa.String(length=8), nullable=False),
    sa.Column('professional_dni', sa.String(length=8), nullable=False),
    sa.Column('appointment_date', sa.DateTime(), nullable=False),
    sa.Column('status', sa.Enum('SCHEDULED', 'COMPLETED', 'CANCELED', name='appointmentstatus'), nullable=False),
    sa.ForeignKeyConstraint(['member_dni'], ['members.dni'], ),
    sa.ForeignKeyConstraint(['professional_dni'], ['professionals.dni'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('member_id', sa.String(length=8), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('period', sa.Date(), nullable=False),
    sa.Column('payment_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['member_id'], ['members.dni'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('activity_enrollments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('member_dni', sa.String(length=8), nullable=False),
    sa.Column('activity_id', sa.Integer(), nullable=False),
    sa.Column('enrollment_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'SUSPENDED', 'CANCELED', name='activitystatus'), nullable=False),
    sa.ForeignKeyConstraint(['activity_id'], ['activities.id'], ),
    sa.ForeignKeyConstraint(['member_dni'], ['members.dni'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('activity_enrollments')
    op.drop_table('payments')
    op.drop_table('appointments')
    op.drop_table('activities')
    op.drop_table('teachers')
    op.drop_table('professionals')
    op.drop_table('members')
    # ### end Alembic commands ###
